yees

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -13,11 +13,11 @@ jobs:
 
             - name: check that tag matches package.json version
               run: |
-                  pkg_version="v$(jq -r .version < package.json)"
-                  if [[ "${{ github.ref_name }}" != "$pkg_version" ]]; then
-                      echo "Tag ${{ github.ref_name }} does not match package.json version $pkg_version" >&2
-                      exit 1
-                  fi
+                pkg_version="v$(jq -r .version < package.json)"
+                if [[ "${{ github.ref_name }}" != "$pkg_version" ]]; then
+                    echo "Tag ${{ github.ref_name }} does not match package.json version $pkg_version" >&2
+                    exit 1
+                fi
 
             - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json
 
@@ -30,8 +30,15 @@ jobs:
             - name: Install dependencies
               run: pnpm install --frozen-lockfile
 
+            - name: Build web
+              run: pnpm buildWeb --standalone
+
             - name: Build
               run: pnpm build --standalone
+
+            - name: Clean up obsolete files
+              run: |
+                rm -rf dist/extension* Vencord.user.css
 
             - name: Create release and upload assets
               run: |
@@ -39,31 +46,28 @@ jobs:
               env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-            - name: Build web
-              run: pnpm buildWeb --standalone
-
             - name: Publish extension
               run: |
-                  cd dist/extension-unpacked
+                cd dist/extension-unpacked
 
-                  # Do not fail so that even if chrome fails, firefox gets a shot. But also store exit code to fail workflow later
-                  EXIT_CODE=0
+                # Do not fail so that even if chrome fails, firefox gets a shot. But also store exit code to fail workflow later
+                EXIT_CODE=0
 
-                  # Chrome
-                  pnpx chrome-webstore-upload-cli@2.1.0 upload --auto-publish || EXIT_CODE=$?
+                # Chrome
+                pnpx chrome-webstore-upload-cli@2.1.0 upload --auto-publish || EXIT_CODE=$?
 
-                  # Firefox
-                  npm i -g web-ext@7.4.0 web-ext-submit@7.4.0
-                  web-ext-submit || EXIT_CODE=$?
+                # Firefox
+                npm i -g web-ext@7.4.0 web-ext-submit@7.4.0
+                web-ext-submit || EXIT_CODE=$?
 
-                  exit $EXIT_CODE
+                exit $EXIT_CODE
               env:
-                  # Chrome
-                  EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
-                  CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
-                  CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
-                  REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
+                # Chrome
+                EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
+                CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
+                CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
+                REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
 
-                  # Firefox
-                  WEB_EXT_API_KEY: ${{ secrets.WEBEXT_USER }}
-                  WEB_EXT_API_SECRET: ${{ secrets.WEBEXT_SECRET }}
+                # Firefox
+                WEB_EXT_API_KEY: ${{ secrets.WEBEXT_USER }}
+                WEB_EXT_API_SECRET: ${{ secrets.WEBEXT_SECRET }}
