Revert "WhosWatching Updates (#1)" (#2)
This reverts commit 410bd1c50f53b1d9d5f592df4fdc8019358038cf.

diff --git a/.github/workflows/reportBrokenPlugins.yml b/.github/workflows/reportBrokenPlugins.yml
--- a/.github/workflows/reportBrokenPlugins.yml
+++ b/.github/workflows/reportBrokenPlugins.yml
@@ -1,22 +1,9 @@
 name: Test Patches
 on:
     workflow_dispatch:
-        inputs:
-            discord_branch:
-                type: choice
-                description: "Discord Branch to test patches on"
-                options:
-                    - both
-                    - stable
-                    - canary
-                default: both
-            webhook_url:
-                type: string
-                description: "Webhook URL that the report will be posted to. This will be visible for everyone, so DO NOT pass sensitive webhooks like discord webhook. This is meant to be used by Venbot."
-                required: false
-    # schedule:
-    #   # Every day at midnight
-    #   - cron: 0 0 * * *
+    schedule:
+        # Every day at midnight
+        - cron: 0 0 * * *
 
 jobs:
     TestPlugins:
@@ -53,43 +40,28 @@ jobs:
             - name: Build Vencord Reporter Version
               run: pnpm buildReporter
 
-            - name: Run Reporter
+            - name: Create Report
               timeout-minutes: 10
               run: |
                   export PATH="$PWD/node_modules/.bin:$PATH"
                   export CHROMIUM_BIN=${{ steps.setup-chrome.outputs.chrome-path }}
 
                   esbuild scripts/generateReport.ts > dist/report.mjs
-
-                  stable_output_file=$(mktemp)
-                  canary_output_file=$(mktemp)
-
-                  pids=""
-
-                  branch="${{ inputs.discord_branch }}"
-                  if [[ "${{ github.event_name }}" = "schedule" ]]; then
-                    branch="both"
-                  fi
-
-                  if [[ "$branch" = "both" || "$branch" = "stable" ]]; then
-                    node dist/report.mjs > "$stable_output_file" &
-                    pids+=" $!"
-                  fi
-
-                  if [[ "$branch" = "both" || "$branch" = "canary" ]]; then
-                    USE_CANARY=true node dist/report.mjs > "$canary_output_file" &
-                    pids+=" $!"
-                  fi
-
-                  exit_code=0
-                  for pid in $pids; do
-                      if ! wait "$pid"; then
-                        exit_code=1
-                      fi
-                  done
-
-                  cat "$stable_output_file" "$canary_output_file" >> $GITHUB_STEP_SUMMARY
-                  exit $exit_code
+                  node dist/report.mjs >> $GITHUB_STEP_SUMMARY
               env:
-                  WEBHOOK_URL: ${{ inputs.webhook_url || secrets.DISCORD_WEBHOOK }}
-                  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
+                  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
+                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
+
+            - name: Create Report (Canary)
+              timeout-minutes: 10
+              if: success() || failure() # even run if previous one failed
+              run: |
+                  export PATH="$PWD/node_modules/.bin:$PATH"
+                  export CHROMIUM_BIN=${{ steps.setup-chrome.outputs.chrome-path }}
+                  export USE_CANARY=true
+
+                  esbuild scripts/generateReport.ts > dist/report.mjs
+                  node dist/report.mjs >> $GITHUB_STEP_SUMMARY
+              env:
+                  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
+                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
